/**
 * Application constants
 */

export const APP_NAME = 'ShrimpWorks';
export const APP_VERSION = '0.0.1';

// Agent Types
export const AGENT_TYPES = {
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  PRODUCT_MANAGER: 'PRODUCT_MANAGER',
  SCRUM_MASTER: 'SCRUM_MASTER',
  ARCHITECT: 'ARCHITECT',
  FRONTEND_DEVELOPER: 'FRONTEND_DEVELOPER',
  BACKEND_DEVELOPER: 'BACKEND_DEVELOPER',
  FULL_STACK_DEVELOPER: 'FULL_STACK_DEVELOPER',
  DEVOPS_ENGINEER: 'DEVOPS_ENGINEER',
  QA_ENGINEER: 'QA_ENGINEER',
  DATA_ENGINEER: 'DATA_ENGINEER',
  DATA_SCIENTIST: 'DATA_SCIENTIST',
  AI_ML_ENGINEER: 'AI_ML_ENGINEER',
  UI_UX_DESIGNER: 'UI_UX_DESIGNER',
  TECHNICAL_WRITER: 'TECHNICAL_WRITER',
  SECURITY_ENGINEER: 'SECURITY_ENGINEER',
  SRE: 'SRE',
  CODE_REVIEWER: 'CODE_REVIEWER',
  PROMPT_ENGINEER: 'PROMPT_ENGINEER',
} as const;

// Task Statuses
export const TASK_STATUSES = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  BLOCKED: 'BLOCKED',
  REVIEW: 'REVIEW',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

// Task Priorities
export const TASK_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

// Project Statuses
export const PROJECT_STATUSES = {
  PLANNING: 'PLANNING',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED',
} as const;

// Workflow Triggers
export const WORKFLOW_TRIGGERS = {
  MANUAL: 'MANUAL',
  SCHEDULED: 'SCHEDULED',
  EVENT: 'EVENT',
  WEBHOOK: 'WEBHOOK',
} as const;

// Execution Statuses
export const EXECUTION_STATUSES = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;
